name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-functions:
    if: contains(github.event.head_commit.message, '[functions]') || 
        steps.filter.outputs.changes == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes in functions/
        id: filter
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^functions/'; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        if: steps.filter.outputs.changes == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Firebase functions typically use 18 or 16

      - name: Install dependencies
        if: steps.filter.outputs.changes == 'true'
        run: cd functions && npm install

      - name: Deploy Firebase Functions
        if: steps.filter.outputs.changes == 'true'
        run: |
          curl -sL https://firebase.tools | bash
          firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
