name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for accurate diff

      - name: Check for changes in functions/ or commit message
        id: should-deploy
        run: |
          # Check if commit message contains [functions]
          if echo "${{ github.event.head_commit.message }}" | grep -q '\[functions\]'; then
            echo "deploy=true" >> $GITHUB_OUTPUT
            echo "Deployment triggered by commit message flag"
            exit 0
          fi
          
          # Check if there are changes in functions/ directory
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^functions/'; then
            echo "deploy=true" >> $GITHUB_OUTPUT
            echo "Deployment triggered by changes in functions/ directory"
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
            echo "No changes in functions/ directory and no [functions] flag in commit message"
          fi

      - name: Set up Node.js
        if: steps.should-deploy.outputs.deploy == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        if: steps.should-deploy.outputs.deploy == 'true'
        run: cd functions && npm install

      - name: Install Firebase CLI
        if: steps.should-deploy.outputs.deploy == 'true'
        run: npm install -g firebase-tools

      - name: Deploy Firebase Functions
        if: steps.should-deploy.outputs.deploy == 'true'
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}